//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/02_Code/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/02_Code/Input/PlayerInputActions.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInputActions: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""6e51adb3-ae68-4382-9cc1-41c032ae2df9"",
            ""actions"": [
                {
                    ""name"": ""RightPlayer1"",
                    ""type"": ""Button"",
                    ""id"": ""1967f4ec-5a41-4fb8-a7a0-6e0e48e5aad0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightPlayer2"",
                    ""type"": ""Button"",
                    ""id"": ""966b0e95-34e1-4765-ad22-f6e27341afef"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPlayer1"",
                    ""type"": ""Button"",
                    ""id"": ""eb3197c5-6cdc-4118-b09c-b2cafe90d485"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftPlayer2"",
                    ""type"": ""Button"",
                    ""id"": ""85527f82-fa30-4e0d-94bb-fdb99f16d18b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpPlayer1"",
                    ""type"": ""Button"",
                    ""id"": ""4e8929f3-75f1-499b-9324-a786e6ebef1b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JumpPlayer2"",
                    ""type"": ""Button"",
                    ""id"": ""8c2f05d1-0f45-4b6d-9e6d-7f30b561286f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlidePlayer1"",
                    ""type"": ""Button"",
                    ""id"": ""ff88061c-b079-49fa-b826-6969c569b58b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SlidePlayer2"",
                    ""type"": ""Button"",
                    ""id"": ""0ab80ed1-f45c-4df5-ac02-7cedd9587e99"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mask1Player1"",
                    ""type"": ""Button"",
                    ""id"": ""e0db7b1b-3963-4b21-a1a4-f4cb543bb25b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mask1Player2"",
                    ""type"": ""Button"",
                    ""id"": ""4965e556-f392-41f2-8e7b-4bb53b2fb514"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mask2Player1"",
                    ""type"": ""Button"",
                    ""id"": ""715a3a81-c5ff-4dbc-9817-f462e9af51a6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mask2Player2"",
                    ""type"": ""Button"",
                    ""id"": ""e3abfbd4-acbd-4351-baa6-c6c8c57103c3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mask3Player1"",
                    ""type"": ""Button"",
                    ""id"": ""d3bb945c-0736-41d8-8737-d552b53a6ece"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mask3Player2"",
                    ""type"": ""Button"",
                    ""id"": ""2b47b631-2407-476c-9a14-045e4749b87c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrevMaskPlayer1"",
                    ""type"": ""Button"",
                    ""id"": ""b1b7f020-dd4f-44bb-91ab-c5d68cc4e3de"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrevMaskPlayer2"",
                    ""type"": ""Button"",
                    ""id"": ""7a8255c4-45ba-4853-a0b1-2a4ed069055b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextMaskPlayer1"",
                    ""type"": ""Button"",
                    ""id"": ""bddee44f-11d9-4856-85c8-bdffbd044d13"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextMaskPlayer2"",
                    ""type"": ""Button"",
                    ""id"": ""eab2ffaa-1102-4bc9-9e47-d6d4786698b8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseMaskPlayer1"",
                    ""type"": ""Button"",
                    ""id"": ""373ebbad-c758-4cbc-8e8d-24da85f79b29"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseMaskPlayer2"",
                    ""type"": ""Button"",
                    ""id"": ""790b7f42-1c85-4788-a2ad-29fde9724e81"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""fdf4a53c-a2c2-4482-aaae-79b7fec24abd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b1b8e56e-62cc-4854-9f60-df1e3b35f17b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43b43cf3-97c0-4097-916f-e79bcf309c30"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c72b379-2525-47f6-aaa8-613b4020bc22"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e561894-b091-4415-9c97-af80ed051bed"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba84367e-d58b-49b4-9e5d-8a54e94ff715"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpPlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""39da35e5-5ab9-4d48-b956-8482b6fac885"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JumpPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""60ec399b-fee1-4050-b296-86c3965402b1"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlidePlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b9c8641-edd6-42df-b3e5-f618918f3e3a"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SlidePlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8481db69-20aa-43c9-b4b1-03ad13587ef0"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mask1Player1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b6a81ab-53bb-4bd3-b7c4-e2cd8e6226dd"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mask1Player2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7c782e1-0e1b-435b-97a1-95df7e6f9263"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mask2Player1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""353b48e4-d356-4983-a6ec-d83df200d8b4"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mask2Player2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""195220f8-7c43-4813-8012-527dabc4b9b2"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mask3Player1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e2696a1-69b0-4fc7-9071-8d1318538d1e"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mask3Player2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8168ac9-028a-4d5b-a9c6-9cb5ac52a8a9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevMaskPlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c634355f-1233-45ab-8dd8-c47c219f521c"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrevMaskPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""43d63fee-c20e-4c30-9c5e-cb51c5a01cea"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextMaskPlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7fb91412-e5cc-441f-813f-ad4d007b612d"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextMaskPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7eb0e7cb-04fb-4977-8636-95f5ed551b08"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseMaskPlayer1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7452b1e3-9398-4209-b719-ae01e26fb3b9"",
                    ""path"": ""<Keyboard>/ö"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseMaskPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1fc25cf8-05ab-441f-8aaf-4d4e9743e9f9"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseMaskPlayer2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aced2b86-7c37-48db-b91c-7c91f89e03ff"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_RightPlayer1 = m_Player.FindAction("RightPlayer1", throwIfNotFound: true);
        m_Player_RightPlayer2 = m_Player.FindAction("RightPlayer2", throwIfNotFound: true);
        m_Player_LeftPlayer1 = m_Player.FindAction("LeftPlayer1", throwIfNotFound: true);
        m_Player_LeftPlayer2 = m_Player.FindAction("LeftPlayer2", throwIfNotFound: true);
        m_Player_JumpPlayer1 = m_Player.FindAction("JumpPlayer1", throwIfNotFound: true);
        m_Player_JumpPlayer2 = m_Player.FindAction("JumpPlayer2", throwIfNotFound: true);
        m_Player_SlidePlayer1 = m_Player.FindAction("SlidePlayer1", throwIfNotFound: true);
        m_Player_SlidePlayer2 = m_Player.FindAction("SlidePlayer2", throwIfNotFound: true);
        m_Player_Mask1Player1 = m_Player.FindAction("Mask1Player1", throwIfNotFound: true);
        m_Player_Mask1Player2 = m_Player.FindAction("Mask1Player2", throwIfNotFound: true);
        m_Player_Mask2Player1 = m_Player.FindAction("Mask2Player1", throwIfNotFound: true);
        m_Player_Mask2Player2 = m_Player.FindAction("Mask2Player2", throwIfNotFound: true);
        m_Player_Mask3Player1 = m_Player.FindAction("Mask3Player1", throwIfNotFound: true);
        m_Player_Mask3Player2 = m_Player.FindAction("Mask3Player2", throwIfNotFound: true);
        m_Player_PrevMaskPlayer1 = m_Player.FindAction("PrevMaskPlayer1", throwIfNotFound: true);
        m_Player_PrevMaskPlayer2 = m_Player.FindAction("PrevMaskPlayer2", throwIfNotFound: true);
        m_Player_NextMaskPlayer1 = m_Player.FindAction("NextMaskPlayer1", throwIfNotFound: true);
        m_Player_NextMaskPlayer2 = m_Player.FindAction("NextMaskPlayer2", throwIfNotFound: true);
        m_Player_UseMaskPlayer1 = m_Player.FindAction("UseMaskPlayer1", throwIfNotFound: true);
        m_Player_UseMaskPlayer2 = m_Player.FindAction("UseMaskPlayer2", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
    }

    ~@PlayerInputActions()
    {
        UnityEngine.Debug.Assert(!m_Player.enabled, "This will cause a leak and performance issues, PlayerInputActions.Player.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_RightPlayer1;
    private readonly InputAction m_Player_RightPlayer2;
    private readonly InputAction m_Player_LeftPlayer1;
    private readonly InputAction m_Player_LeftPlayer2;
    private readonly InputAction m_Player_JumpPlayer1;
    private readonly InputAction m_Player_JumpPlayer2;
    private readonly InputAction m_Player_SlidePlayer1;
    private readonly InputAction m_Player_SlidePlayer2;
    private readonly InputAction m_Player_Mask1Player1;
    private readonly InputAction m_Player_Mask1Player2;
    private readonly InputAction m_Player_Mask2Player1;
    private readonly InputAction m_Player_Mask2Player2;
    private readonly InputAction m_Player_Mask3Player1;
    private readonly InputAction m_Player_Mask3Player2;
    private readonly InputAction m_Player_PrevMaskPlayer1;
    private readonly InputAction m_Player_PrevMaskPlayer2;
    private readonly InputAction m_Player_NextMaskPlayer1;
    private readonly InputAction m_Player_NextMaskPlayer2;
    private readonly InputAction m_Player_UseMaskPlayer1;
    private readonly InputAction m_Player_UseMaskPlayer2;
    private readonly InputAction m_Player_Pause;
    /// <summary>
    /// Provides access to input actions defined in input action map "Player".
    /// </summary>
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Player/RightPlayer1".
        /// </summary>
        public InputAction @RightPlayer1 => m_Wrapper.m_Player_RightPlayer1;
        /// <summary>
        /// Provides access to the underlying input action "Player/RightPlayer2".
        /// </summary>
        public InputAction @RightPlayer2 => m_Wrapper.m_Player_RightPlayer2;
        /// <summary>
        /// Provides access to the underlying input action "Player/LeftPlayer1".
        /// </summary>
        public InputAction @LeftPlayer1 => m_Wrapper.m_Player_LeftPlayer1;
        /// <summary>
        /// Provides access to the underlying input action "Player/LeftPlayer2".
        /// </summary>
        public InputAction @LeftPlayer2 => m_Wrapper.m_Player_LeftPlayer2;
        /// <summary>
        /// Provides access to the underlying input action "Player/JumpPlayer1".
        /// </summary>
        public InputAction @JumpPlayer1 => m_Wrapper.m_Player_JumpPlayer1;
        /// <summary>
        /// Provides access to the underlying input action "Player/JumpPlayer2".
        /// </summary>
        public InputAction @JumpPlayer2 => m_Wrapper.m_Player_JumpPlayer2;
        /// <summary>
        /// Provides access to the underlying input action "Player/SlidePlayer1".
        /// </summary>
        public InputAction @SlidePlayer1 => m_Wrapper.m_Player_SlidePlayer1;
        /// <summary>
        /// Provides access to the underlying input action "Player/SlidePlayer2".
        /// </summary>
        public InputAction @SlidePlayer2 => m_Wrapper.m_Player_SlidePlayer2;
        /// <summary>
        /// Provides access to the underlying input action "Player/Mask1Player1".
        /// </summary>
        public InputAction @Mask1Player1 => m_Wrapper.m_Player_Mask1Player1;
        /// <summary>
        /// Provides access to the underlying input action "Player/Mask1Player2".
        /// </summary>
        public InputAction @Mask1Player2 => m_Wrapper.m_Player_Mask1Player2;
        /// <summary>
        /// Provides access to the underlying input action "Player/Mask2Player1".
        /// </summary>
        public InputAction @Mask2Player1 => m_Wrapper.m_Player_Mask2Player1;
        /// <summary>
        /// Provides access to the underlying input action "Player/Mask2Player2".
        /// </summary>
        public InputAction @Mask2Player2 => m_Wrapper.m_Player_Mask2Player2;
        /// <summary>
        /// Provides access to the underlying input action "Player/Mask3Player1".
        /// </summary>
        public InputAction @Mask3Player1 => m_Wrapper.m_Player_Mask3Player1;
        /// <summary>
        /// Provides access to the underlying input action "Player/Mask3Player2".
        /// </summary>
        public InputAction @Mask3Player2 => m_Wrapper.m_Player_Mask3Player2;
        /// <summary>
        /// Provides access to the underlying input action "Player/PrevMaskPlayer1".
        /// </summary>
        public InputAction @PrevMaskPlayer1 => m_Wrapper.m_Player_PrevMaskPlayer1;
        /// <summary>
        /// Provides access to the underlying input action "Player/PrevMaskPlayer2".
        /// </summary>
        public InputAction @PrevMaskPlayer2 => m_Wrapper.m_Player_PrevMaskPlayer2;
        /// <summary>
        /// Provides access to the underlying input action "Player/NextMaskPlayer1".
        /// </summary>
        public InputAction @NextMaskPlayer1 => m_Wrapper.m_Player_NextMaskPlayer1;
        /// <summary>
        /// Provides access to the underlying input action "Player/NextMaskPlayer2".
        /// </summary>
        public InputAction @NextMaskPlayer2 => m_Wrapper.m_Player_NextMaskPlayer2;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseMaskPlayer1".
        /// </summary>
        public InputAction @UseMaskPlayer1 => m_Wrapper.m_Player_UseMaskPlayer1;
        /// <summary>
        /// Provides access to the underlying input action "Player/UseMaskPlayer2".
        /// </summary>
        public InputAction @UseMaskPlayer2 => m_Wrapper.m_Player_UseMaskPlayer2;
        /// <summary>
        /// Provides access to the underlying input action "Player/Pause".
        /// </summary>
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @RightPlayer1.started += instance.OnRightPlayer1;
            @RightPlayer1.performed += instance.OnRightPlayer1;
            @RightPlayer1.canceled += instance.OnRightPlayer1;
            @RightPlayer2.started += instance.OnRightPlayer2;
            @RightPlayer2.performed += instance.OnRightPlayer2;
            @RightPlayer2.canceled += instance.OnRightPlayer2;
            @LeftPlayer1.started += instance.OnLeftPlayer1;
            @LeftPlayer1.performed += instance.OnLeftPlayer1;
            @LeftPlayer1.canceled += instance.OnLeftPlayer1;
            @LeftPlayer2.started += instance.OnLeftPlayer2;
            @LeftPlayer2.performed += instance.OnLeftPlayer2;
            @LeftPlayer2.canceled += instance.OnLeftPlayer2;
            @JumpPlayer1.started += instance.OnJumpPlayer1;
            @JumpPlayer1.performed += instance.OnJumpPlayer1;
            @JumpPlayer1.canceled += instance.OnJumpPlayer1;
            @JumpPlayer2.started += instance.OnJumpPlayer2;
            @JumpPlayer2.performed += instance.OnJumpPlayer2;
            @JumpPlayer2.canceled += instance.OnJumpPlayer2;
            @SlidePlayer1.started += instance.OnSlidePlayer1;
            @SlidePlayer1.performed += instance.OnSlidePlayer1;
            @SlidePlayer1.canceled += instance.OnSlidePlayer1;
            @SlidePlayer2.started += instance.OnSlidePlayer2;
            @SlidePlayer2.performed += instance.OnSlidePlayer2;
            @SlidePlayer2.canceled += instance.OnSlidePlayer2;
            @Mask1Player1.started += instance.OnMask1Player1;
            @Mask1Player1.performed += instance.OnMask1Player1;
            @Mask1Player1.canceled += instance.OnMask1Player1;
            @Mask1Player2.started += instance.OnMask1Player2;
            @Mask1Player2.performed += instance.OnMask1Player2;
            @Mask1Player2.canceled += instance.OnMask1Player2;
            @Mask2Player1.started += instance.OnMask2Player1;
            @Mask2Player1.performed += instance.OnMask2Player1;
            @Mask2Player1.canceled += instance.OnMask2Player1;
            @Mask2Player2.started += instance.OnMask2Player2;
            @Mask2Player2.performed += instance.OnMask2Player2;
            @Mask2Player2.canceled += instance.OnMask2Player2;
            @Mask3Player1.started += instance.OnMask3Player1;
            @Mask3Player1.performed += instance.OnMask3Player1;
            @Mask3Player1.canceled += instance.OnMask3Player1;
            @Mask3Player2.started += instance.OnMask3Player2;
            @Mask3Player2.performed += instance.OnMask3Player2;
            @Mask3Player2.canceled += instance.OnMask3Player2;
            @PrevMaskPlayer1.started += instance.OnPrevMaskPlayer1;
            @PrevMaskPlayer1.performed += instance.OnPrevMaskPlayer1;
            @PrevMaskPlayer1.canceled += instance.OnPrevMaskPlayer1;
            @PrevMaskPlayer2.started += instance.OnPrevMaskPlayer2;
            @PrevMaskPlayer2.performed += instance.OnPrevMaskPlayer2;
            @PrevMaskPlayer2.canceled += instance.OnPrevMaskPlayer2;
            @NextMaskPlayer1.started += instance.OnNextMaskPlayer1;
            @NextMaskPlayer1.performed += instance.OnNextMaskPlayer1;
            @NextMaskPlayer1.canceled += instance.OnNextMaskPlayer1;
            @NextMaskPlayer2.started += instance.OnNextMaskPlayer2;
            @NextMaskPlayer2.performed += instance.OnNextMaskPlayer2;
            @NextMaskPlayer2.canceled += instance.OnNextMaskPlayer2;
            @UseMaskPlayer1.started += instance.OnUseMaskPlayer1;
            @UseMaskPlayer1.performed += instance.OnUseMaskPlayer1;
            @UseMaskPlayer1.canceled += instance.OnUseMaskPlayer1;
            @UseMaskPlayer2.started += instance.OnUseMaskPlayer2;
            @UseMaskPlayer2.performed += instance.OnUseMaskPlayer2;
            @UseMaskPlayer2.canceled += instance.OnUseMaskPlayer2;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerActions" />
        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @RightPlayer1.started -= instance.OnRightPlayer1;
            @RightPlayer1.performed -= instance.OnRightPlayer1;
            @RightPlayer1.canceled -= instance.OnRightPlayer1;
            @RightPlayer2.started -= instance.OnRightPlayer2;
            @RightPlayer2.performed -= instance.OnRightPlayer2;
            @RightPlayer2.canceled -= instance.OnRightPlayer2;
            @LeftPlayer1.started -= instance.OnLeftPlayer1;
            @LeftPlayer1.performed -= instance.OnLeftPlayer1;
            @LeftPlayer1.canceled -= instance.OnLeftPlayer1;
            @LeftPlayer2.started -= instance.OnLeftPlayer2;
            @LeftPlayer2.performed -= instance.OnLeftPlayer2;
            @LeftPlayer2.canceled -= instance.OnLeftPlayer2;
            @JumpPlayer1.started -= instance.OnJumpPlayer1;
            @JumpPlayer1.performed -= instance.OnJumpPlayer1;
            @JumpPlayer1.canceled -= instance.OnJumpPlayer1;
            @JumpPlayer2.started -= instance.OnJumpPlayer2;
            @JumpPlayer2.performed -= instance.OnJumpPlayer2;
            @JumpPlayer2.canceled -= instance.OnJumpPlayer2;
            @SlidePlayer1.started -= instance.OnSlidePlayer1;
            @SlidePlayer1.performed -= instance.OnSlidePlayer1;
            @SlidePlayer1.canceled -= instance.OnSlidePlayer1;
            @SlidePlayer2.started -= instance.OnSlidePlayer2;
            @SlidePlayer2.performed -= instance.OnSlidePlayer2;
            @SlidePlayer2.canceled -= instance.OnSlidePlayer2;
            @Mask1Player1.started -= instance.OnMask1Player1;
            @Mask1Player1.performed -= instance.OnMask1Player1;
            @Mask1Player1.canceled -= instance.OnMask1Player1;
            @Mask1Player2.started -= instance.OnMask1Player2;
            @Mask1Player2.performed -= instance.OnMask1Player2;
            @Mask1Player2.canceled -= instance.OnMask1Player2;
            @Mask2Player1.started -= instance.OnMask2Player1;
            @Mask2Player1.performed -= instance.OnMask2Player1;
            @Mask2Player1.canceled -= instance.OnMask2Player1;
            @Mask2Player2.started -= instance.OnMask2Player2;
            @Mask2Player2.performed -= instance.OnMask2Player2;
            @Mask2Player2.canceled -= instance.OnMask2Player2;
            @Mask3Player1.started -= instance.OnMask3Player1;
            @Mask3Player1.performed -= instance.OnMask3Player1;
            @Mask3Player1.canceled -= instance.OnMask3Player1;
            @Mask3Player2.started -= instance.OnMask3Player2;
            @Mask3Player2.performed -= instance.OnMask3Player2;
            @Mask3Player2.canceled -= instance.OnMask3Player2;
            @PrevMaskPlayer1.started -= instance.OnPrevMaskPlayer1;
            @PrevMaskPlayer1.performed -= instance.OnPrevMaskPlayer1;
            @PrevMaskPlayer1.canceled -= instance.OnPrevMaskPlayer1;
            @PrevMaskPlayer2.started -= instance.OnPrevMaskPlayer2;
            @PrevMaskPlayer2.performed -= instance.OnPrevMaskPlayer2;
            @PrevMaskPlayer2.canceled -= instance.OnPrevMaskPlayer2;
            @NextMaskPlayer1.started -= instance.OnNextMaskPlayer1;
            @NextMaskPlayer1.performed -= instance.OnNextMaskPlayer1;
            @NextMaskPlayer1.canceled -= instance.OnNextMaskPlayer1;
            @NextMaskPlayer2.started -= instance.OnNextMaskPlayer2;
            @NextMaskPlayer2.performed -= instance.OnNextMaskPlayer2;
            @NextMaskPlayer2.canceled -= instance.OnNextMaskPlayer2;
            @UseMaskPlayer1.started -= instance.OnUseMaskPlayer1;
            @UseMaskPlayer1.performed -= instance.OnUseMaskPlayer1;
            @UseMaskPlayer1.canceled -= instance.OnUseMaskPlayer1;
            @UseMaskPlayer2.started -= instance.OnUseMaskPlayer2;
            @UseMaskPlayer2.performed -= instance.OnUseMaskPlayer2;
            @UseMaskPlayer2.canceled -= instance.OnUseMaskPlayer2;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />.
        /// </summary>
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
        /// <seealso cref="PlayerActions.UnregisterCallbacks(IPlayerActions)" />
        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerActions" /> instance referencing this action map.
    /// </summary>
    public PlayerActions @Player => new PlayerActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Player" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerActions.AddCallbacks(IPlayerActions)" />
    /// <seealso cref="PlayerActions.RemoveCallbacks(IPlayerActions)" />
    public interface IPlayerActions
    {
        /// <summary>
        /// Method invoked when associated input action "RightPlayer1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightPlayer1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightPlayer2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightPlayer2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftPlayer1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftPlayer1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftPlayer2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftPlayer2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "JumpPlayer1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJumpPlayer1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "JumpPlayer2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnJumpPlayer2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SlidePlayer1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSlidePlayer1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "SlidePlayer2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnSlidePlayer2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mask1Player1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMask1Player1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mask1Player2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMask1Player2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mask2Player1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMask2Player1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mask2Player2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMask2Player2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mask3Player1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMask3Player1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Mask3Player2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMask3Player2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PrevMaskPlayer1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrevMaskPlayer1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "PrevMaskPlayer2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPrevMaskPlayer2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NextMaskPlayer1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNextMaskPlayer1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NextMaskPlayer2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNextMaskPlayer2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseMaskPlayer1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseMaskPlayer1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "UseMaskPlayer2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnUseMaskPlayer2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Pause" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPause(InputAction.CallbackContext context);
    }
}
